name: flutter_corelib
description: "A new Flutter package project."
version: 0.0.3
homepage: https://github.com/Glitch9Inc/flutter_corelib
git:
  url: https://github.com/Glitch9Inc/flutter_corelib
  ref: main

environment:
  sdk: ">=3.3.4 <4.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

  intl: ^0.19.0 # Localization
  shared_preferences: ^2.0.8 # For PlayerPrefs (unity-style)
  assets_audio_player: ^3.1.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  build_runner: ^2.4.9
  dart_code_metrics: ^5.7.6
  test: ^1.24.3
