name: flutter_corelib
description: "A comprehensive library for Flutter applications, providing utilities for management, local database, network operations, audio, localization, UI, and more."
version: 0.2.4
homepage: https://github.com/Glitch9Inc/flutter_corelib
repository: https://github.com/Glitch9Inc/flutter_corelib
issue_tracker: https://github.com/Glitch9Inc/flutter_corelib/issues
documentation: https://github.com/Glitch9Inc/flutter_corelib#readme
publish_to: "none" # Remove this line to publish to pub.dev

environment:
  sdk: ">=3.3.4 <4.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

  # management
  logging: ^1.2.0
  path_provider: ^2.0.11
  get: ^4.6.5
  path: ^1.9.0
  url_launcher: ^6.2.6
  uuid: ^4.4.2
  freezed_annotation: ^2.4.4
  in_app_purchase: ^3.2.0 # Monitization
  dio: ^5.5.0+1

  # local database
  shared_preferences: ^2.0.8
  csv: ^6.0.0
  hive: ^4.0.0-dev.2
  isar_flutter_libs: ^4.0.0-dev.13

  # audio related
  just_audio: ^0.9.39

  # localization
  intl: ^0.19.0

  # ui related
  auto_size_text: ^3.0.0
  animated_text_kit: ^4.2.2
  syncfusion_flutter_calendar: ^26.1.42
  badges: ^3.1.2

  # Api Services
  cloud_firestore: ^5.0.1

  # Google Services
  googleapis: ^13.2.0
  google_sign_in: ^6.2.1

  # Scratch Card
  scratcher: ^2.5.0

dev_dependencies:
  flutter_lints: ^2.0.0
  build_runner: ^2.4.11
  freezed: ^2.5.2
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
